---
- name: Configure Local ZeroTier Node
  zerotier_node_config:
    networks: "{{ zerotier_networks }}"
    local_api_url: "http://localhost:9993"

- name: Setup ZeroTier Planet
  ansible.builtin.template:
    src: planet.j2
    dest: /var/lib/zerotier-one/planet.custom
    owner: zerotier-one
    group: zerotier-one
    mode: 0644
  when: zerotier_planet != ""
  notify:
    - Stop ZeroTier
    - Start ZeroTier

- name: Build ZeroTier local config
  ansible.builtin.template:
    src: local.conf.j2
    dest: /var/lib/zerotier-one/local.conf
    owner: zerotier-one
    group: zerotier-one
    mode: 0644
  notify:
    - Stop ZeroTier
    - Start ZeroTier

- name: Setup ZeroTier Service Override folder
  ansible.builtin.file:
    path: /etc/systemd/system/zerotier-one.service.d/
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Setup ZeroTier Service Override
  ansible.builtin.copy:
    src: systemd-override.conf
    dest: /etc/systemd/system/zerotier-one.service.d/ansible.conf
    owner: root
    group: root
    mode: '0644'
