---
- name: Configure Local ZeroTier Node
  zerotier_node_config:
    networks: "{{ zerotier_networks }}"
    local_api_url: "http://localhost:9993"

- name: Setup ZeroTier Planet
  template:
    src: planet.j2
    dest: /var/lib/zerotier-one/planet
    owner: zerotier-one
    group: zerotier-one
    mode: 0644
  when: zerotier_planet != ""
  notify:
    - Restart ZeroTier