---
- name: Get ZTNet Node Identity
  ansible.builtin.slurp:
    src: /var/lib/zerotier-one/identity.public
  register: node_identity

- name: Configure ZTNet Central Node Settings
  ztnet_node_config:
    node: "{{ node_identity['content'] | b64decode | split(':') | first }}"
    network: "{{ item }}"
    api_key: "{{ zerotier_ztnet_api_key }}"
    api_url: "{{ zerotier_ztnet_api_base_url }}/api/v1"
    config:
      authorized: true
      name: "{{ inventory_hostname }}"
  loop: "{{ zerotier_networks.keys()|list }}"