---
- name: Setup ZeroTier Node Planet
  ansible.builtin.copy:
    dest: "{{ zerotier_node_home }}/planet.custom"
    owner: zerotier-one
    group: zerotier-one
    mode: "0644"
    content: "{{ zerotier_node_planet | b64decode }}"
  when: zerotier_node_planet != ""
  register: zerotier_node_planet

- name: Build ZeroTier Node local config
  ansible.builtin.copy:
    dest: "{{ zerotier_node_home }}/local.conf"
    owner: zerotier-one
    group: zerotier-one
    mode: "0644"
    content: "{{ zerotier_node_localconfig | to_nice_json }}"
  register: zerotier_node_localconfig

- name: Restart ZeroTier if Planet or Local Config are changed
  ansible.builtin.systemd_service:
    name: zerotier-one.service
    state: restarted
  when: zerotier_node_planet.changed or zerotier_node_localconfig.changed

- name: Configure ZeroTier Node
  zerotier_node_config:
    networks: "{{ zerotier_node_networks }}"
    local_api_url: "http://localhost:{{ zerotier_node_localconfig['settings']['primaryPort'] }}"
