---
- name: Add host to ZeroTier Network
  ztnet_node_config:
    node: "{{ lookup('ansible.builtin.file', '/var/lib/zerotier-one/identity.public') |  split(':') | first }}"
    network: "{{ item }}"
    api_key: "{{ zerotier_ztnet_api_key }}"
    api_url: "{{ zerotier_ztnet_api_base_url }}/api/v1"
    config:
      authorized: true
      name: "{{ inventory_hostname }}"
  loop: "{{ zerotier_networks.keys()|list }}"