---
- name: Add host to ZeroTier Network
  ztnet_node_config:
    node: "{{ inventory_hostname }}"
    network: "{{ item }}"
    api_key: "{{ zerotier_ztnet_api_key }}"
    api_url: "{{ zerotier_ztnet_api_url }}/api/v1"
    config:
      authorized: true
  loop: "{{ zerotier_networks.keys()|list }}"