---
- name: Install Prerequisite Packages
  ansible.builtin.apt:
    update_cache: true
    state: present
    pkg: "{{ osmap[ansible_facts['distribution'] | lower][ansible_distribution_release | lower]['packages'] }}"

- name: Add ZeroTier GPG Key
  ansible.builtin.apt_key:
    url: "{{ zerotier_repo['gpg'] }}"
    state: present

- name: Add ZeroTier Repo
  ansible.builtin.apt_repository:
    repo: "{{ osmap[ansible_facts['distribution'] | lower][ansible_distribution_release | lower]['zerotier_repo'] }}"

- name: Install ZeroTier
  ansible.builtin.apt:
    name: zerotier-one={{ zerotier_version }}
    state: present
    update_cache: true
    allow_downgrade: true
