---
- name: Include OS Specific mappings
  include_vars:
    file: osmap.yaml
    name: osmap

- name: Install ZeroTier (DEB)
  include_tasks: install_deb.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Install ZeroTier (RPM)
  include_tasks: install_rpm.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable ZeroTier Service
  systemd:
    name: zerotier-one
    state: started
    enabled: yes

- name: Wait for ZeroTier to generate identity
  wait_for:
    path: /var/lib/zerotier-one/identity.secret

- name: Perform Local Config
  include_tasks: local_config.yml

- name: Setup ZeroTier Network Directory
  ansible.builtin.file:
    path: /var/lib/zerotier-one/networks.d/
    state: directory
    mode: '0755'
    owner: zerotier-one
    group: zerotier-one
  notify:
    - Restart ZeroTier

- name: Setup ZeroTier Networks
  ansible.builtin.file:
    path: /var/lib/zerotier-one/networks.d/{{ item }}.conf
    state: touch
    mode: 0644
    owner: zerotier-one
    group: zerotier-one
    creates: /var/lib/zerotier-one/networks.d/{{ item }}.conf
  loop: "{{ zerotier_networks.keys()|list }}"
  notify:
    - Restart ZeroTier

- name: Setup ZeroTier Planet
  template:
    src: planet.j2
    dest: /var/lib/zerotier-one/planet
    owner: zerotier-one
    group: zerotier-one
    mode: 0644
  when: zerotier_planet != ""
  notify:
    - Restart ZeroTier

- name: Configure ZTNET
  include_tasks: configure_ztnet.yml