---
- name: Include OS Specific mappings
  include_vars:
    file: osmap.yaml
    name: osmap

- name: Install ZeroTier (DEB)
  include_tasks: install_deb.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Install ZeroTier (RPM)
  include_tasks: install_rpm.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Wait for ZeroTier to generate identity
  wait_for:
    path: /var/lib/zerotier-one/identity.secret

- name: Perform Local Config
  include_tasks: local_config.yml

- name: Configure ZeroTier
  include_tasks: configure_zerotier.yml

- name: Flush handlers
  meta: flush_handlers

- name: Configure ZTNET
  include_tasks: configure_ztnet.yml