name: commitlint
on:
  pull_request:
    branches: [ master ]
permissions:
  actions: read
  attestations: none
  checks: read
  contents: read
  deployments: none
  id-token: none
  issues: read
  discussions: read
  packages: read
  pages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  commitlint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: ghcr.io/mystarinyoursky/semanticrelease:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        REPO_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fix Permissions
        run: git config --global --add safe.directory /__w/ansible-role-base/ansible-role-base
      - name: Run CommitLint
        run: |
          echo -n "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} | tee /tmp/comment || true
      - name: Send result to GitHub PR
        run: |
          if [ -s /tmp/comment ]; then
            echo '```' > /tmp/formattedcommit
            cat /tmp/comment >> /tmp/formattedcommit
            echo '```' >> /tmp/formattedcommit
            gh pr comment ${PR_NUMBER} --repo "${REPO_NAME}" --body "$(cat /tmp/formattedcommit)"
          else
            echo "No need to send to Github PR"
          fi
