name: CommitLint
on:
  pull_request:
    branches: [ master ]
permissions:
  packages: read
  contents: read
  pull-requests: read
jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/mystarinyoursky/releasetool:latest
    env:
      FORCE_COLOR: 1
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
